_assetic:
    resource: .
    type:     assetic

asterisk_test_app:
    resource: "@AsteriskTestAppBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
